[phases.setup]
nixPkgs = ["nodejs", "chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "expat", "libxcb", "libxkbcommon", "mesa", "alsa-lib"]

[phases.build]
cmds = ["npm install"]

[variables]
NIXPACKS_PKGS = "nodejs chromium"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"